[[redirects]]
from = "/optim/:transform/*"
to = "https://res.cloudinary.com/ramble/image/fetch/q_auto,f_auto/t_:transform/https://randolphramble.com/images/:splat"
status = 200

[[redirects]]
from = "/lodging/"
to = "/"
status = 301
