backend:
  name: git-gateway
  branch: main
local_backend: false
media_folder: "/src/images/"
public_folder: "/images/"
site_url: "https://randolphramble.com/"
display_url: "https://randolphramble.com"
collections:

  - name: pages
    label: Pages
    label_singular: Page
    description: "Where you can update the various bits of copy around the site."
    files:
      - name: home
        label: Homepage
        delete: false
        file: src/pages/home.md
        slug: '{{slug}}'
        preview_path: /
        fields:
          - label: Title
            name: title
            widget: hidden
            default: Home
          - label: Permalink
            name: permalink
            widget: hidden
            default: /
          - label: Order
            name: order
            widget: hidden
            default: 0
          - label: Body
            name: body
            widget: markdown
            buttons: ['bold', 'italic', 'link', 'heading-three', 'heading-four', 'heading-five', 'heading-six', 'quote', 'bulleted-list', 'numbered-list']
            editor_components: ['image']

      - name: course
        label: Course
        delete: false
        file: src/pages/course.md
        slug: '{{slug}}'
        preview_path: /course/
        fields:
          - label: Title
            name: title
            widget: hidden
            default: The Course
          - label: Permalink
            name: permalink
            widget: hidden
            default: /course/
          - label: Order
            name: order
            widget: hidden
            default: 1
          - label: Body
            name: body
            widget: markdown
            buttons: ['bold', 'italic', 'link', 'heading-three', 'heading-four', 'heading-five', 'heading-six', 'quote', 'bulleted-list', 'numbered-list']
            editor_components: ['image']
            minimal: true

      - name: important-info
        label: Important Info
        delete: false
        file: src/pages/important-info.md
        slug: '{{slug}}'
        preview_path: /important-info/
        fields:
          - label: Title
            name: title
            widget: hidden
            default: Important Info
          - label: Permalink
            name: permalink
            widget: hidden
            default: /important-info/
          - label: Order
            name: order
            widget: hidden
            default: 2
          - label: Body
            name: body
            widget: markdown
            buttons: ['bold', 'italic', 'link', 'heading-three', 'heading-four', 'heading-five', 'heading-six', 'quote', 'bulleted-list', 'numbered-list']
            editor_components: ['image']
            minimal: true

      - name: registration-schedule
        label: Registration and Schedule
        delete: false
        file: src/pages/registration-schedule.md
        slug: '{{slug}}'
        preview_path: /registration-schedule/
        fields:
          - label: Title
            name: title
            widget: hidden
            default: Registration and Schedule
          - label: Permalink
            name: permalink
            widget: hidden
            default: /registration-schedule/
          - label: Order
            name: order
            widget: hidden
            default: 3
          - label: Body
            name: body
            widget: markdown
            buttons: ['bold', 'italic', 'link', 'heading-three', 'heading-four', 'heading-five', 'heading-six', 'quote', 'bulleted-list', 'numbered-list']
            editor_components: ['image']
            minimal: true

      - name: sponsors
        label: Sponsors
        delete: false
        file: src/pages/sponsors.md
        slug: '{{slug}}'
        preview_path: /sponsors/
        fields:
          - label: Title
            name: title
            widget: hidden
            default: Sponsors
          - label: Permalink
            name: permalink
            widget: hidden
            default: /sponsors/
          - label: Order
            name: order
            widget: hidden
            default: 4
          - label: Body
            name: body
            widget: markdown
            buttons: ['bold', 'italic', 'link', 'heading-three', 'heading-four', 'heading-five', 'heading-six', 'quote', 'bulleted-list', 'numbered-list']
            editor_components: ['image']
            minimal: true
          - label: Sponsors
            label_singular: Sponsor
            name: sponsors
            widget: list
            allow_add: true
            collapsed: true
            add_to_top: true
            summary: '{{fields.name}}'
            preview_path: /sponsors/
            fields:
              - label: Sponsor Name
                name: name
                widget: string
                hint: "Sponsor name"
                required: true
              - label: Sponsor Logo
                name: logo_file
                widget: image
                allow_multiple: false
              - label: Sponsor Link
                name: link
                widget: string
                hint: "Link to sponsor's website"
              - label: Sponsor Logo Width
                name: logo_width
                widget: number
                hint: "Sponsor logo's width if you know it"
              - label: Sponsor Logo Height
                name: logo_height
                widget: number
                hint: "Sponsor logo's height if you know it"

      - name: contact
        label: Contact
        delete: false
        file: src/pages/contact.md
        slug: '{{slug}}'
        preview_path: /contact/
        fields:
          - label: Title
            name: title
            widget: hidden
            default: Contact
          - label: Permalink
            name: permalink
            widget: hidden
            default: /contact/
          - label: Order
            name: order
            widget: hidden
            default: 5
          - label: Body
            name: body
            widget: markdown
            buttons: ['bold', 'italic', 'link', 'heading-three', 'heading-four', 'heading-five', 'heading-six', 'quote', 'bulleted-list', 'numbered-list']
            editor_components: ['image']
            minimal: true

      - name: thank-you
        label: Thank You
        delete: false
        file: src/pages/thank-you.md
        slug: '{{slug}}'
        preview_path: /contact/thank-you/
        fields:
          - label: Title
            name: title
            widget: hidden
            default: Thank You
          - label: Permalink
            name: permalink
            widget: hidden
            default: /contact/thank-you/
          - label: Order
            name: order
            widget: hidden
            default: 13
          - label: Exclude from Collections
            name: eleventyExcludeFromCollections
            widget: hidden
            default: true
          - label: Body
            name: body
            widget: markdown
            buttons: ['bold', 'italic', 'link', 'heading-three', 'heading-four', 'heading-five', 'heading-six', 'quote', 'bulleted-list', 'numbered-list']
            editor_components: ['image']
            minimal: true

      - name: error-404
        label: Error (404)
        delete: false
        file: src/pages/404.md
        slug: '{{slug}}'
        preview_path: /404.html
        fields:
          - label: Title
            name: title
            widget: hidden
            default: Page Not Found (404)
          - label: Permalink
            name: permalink
            widget: hidden
            default: /404.html
          - label: Order
            name: order
            widget: hidden
            default: 20
          - label: Exclude from Collections
            name: eleventyExcludeFromCollections
            widget: hidden
            default: true
          - label: Body
            name: body
            widget: markdown
            buttons: ['bold', 'italic', 'link', 'heading-three', 'heading-four', 'heading-five', 'heading-six', 'quote', 'bulleted-list', 'numbered-list']
            editor_components: ['image']
            minimal: true

  - name: "Settings"
    label: "Settings"
    description: "Set site and registration settings here"
    files:
      - label: "Site"
        name: "site"
        delete: false
        editor:
          preview: false
        file: "src/_data/site.json"
        fields:
          - label: Site Title
            name: title
            widget: string
            hint: 'Text that appears in search results, when shared on social media, etc.'
          - label: Site Description
            name: description
            widget: text
            hint: >-
              Text that appears below title in search results and sometimes on social
              media. Google truncates around 160 characters.
            pattern:
              - '.{1,160}'
              - Should be 160 characters or less.
          - label: Site Url
            name: url
            widget: string
            hint: 'The domain where the site lives'
          - label: Social Share Image
            name: og_img
            widget: image
            allow_multiple: false
      - label: "Registration"
        name: "registration"
        delete: false
        editor:
          preview: false
        file: "src/_data/registration.json"
        fields:
          - label: Is Open?
            name: is_open
            widget: boolean
            hint: 'If set to "false" (toggled left - gray), registration buttons throughout the site will be hidden. If set to "true" (toggled right - blue), registration buttons will appear and link field below will be used.'
          - label: Registration Link
            name: link
            widget: string
            hint: 'The address where runners can sign up'
